import { ChromaClient, OpenAIEmbeddingFunction } from "chromadb";

const client = new ChromaClient({
    path: "http://localhost:8000"
});

const embeddingFunction = new OpenAIEmbeddingFunction({
    openai_api_key: process.env.OPENAI_API_KEY,
    openai_model: "text-embedding-3-small"
})

const main = async () => {
    //create a collection 
    const response = await client.createCollection({
        name: "data-set1",
        embeddingFunction: embeddingFunction
    });

    //checks to know the collection was created
    console.log(response);
    console.log("collection name: ", response.name);
}

//add data to the collection

const addData = async () => {
    const collection = await client.getCollection({
        name: "data-set1",
        embeddingFunction: embeddingFunction
    });

    //add collection
    await collection.upsert({
        ids: ["id1"],
        documents: ["bro"],
        // embeddings are mandatory and should be generated by a model
        // embeddings: [[1.2, 3.2]]
    });

    console.log("document added");

    //Query the same content to verify it's there
    const result = await collection.query({
        queryTexts: ["bro"],
        nResults: 1
    });

    console.log("query result", JSON.stringify(result, null, 2))

};

const getAllData = async () => {
    const collection = await client.getCollection({
        name: "data-set1",
        embeddingFunction: embeddingFunction
    });

    // const ids = ["id0", "id2"];

    const result = await collection.get({ limit: 100 });
    // const result = await collection.get({ ids: ids });

    console.log("data: ", JSON.stringify(result, null, 2))
};

const deleteData = async () => {
    const res = await client.deleteCollection({ name: "data-set1" });

    console.log("deleted");
    console.log("response: ", res)
}

// main();
// addData()
getAllData();
// deleteData();
