import { ChromaClient } from "chromadb";

const client = new ChromaClient({
    path: "http://localhost:8000"
});

const main = async () => {
    //create a collection 
    const response = await client.createCollection({
        name: "data-set"
    });

    console.log(response);
    console.log("collection name: ", response.name);
}

//add data to the collection

const addData = async () => {
    const collection = await client.getCollection({
        name: "data-set"
    });

    //add collection
    await collection.add({
        ids: ["id2"],
        documents: ["is"],
        // embeddings are mandatory and should be generated by a model
        embeddings: [[1, 343.5]]
    });

    console.log("document added");

    //Query the same content to verify it's there
    const result = await collection.query({
        queryEmbeddings: [[1, 343.5]],
        nResults: 1
    });

    console.log("query result", JSON.stringify(result, null, 2))

};

const getAllData = async () => {
    const collection = await client.getCollection({
        name: "data-set"
    });

    const ids = ["id0", "id2"];

    // const result = await collection.get({ limit: 100 });
    const result = await collection.get({ ids: ids });

    console.log("data: ", JSON.stringify(result, null, 2))
}

getAllData();
// addData()

// main();